# Generated by Django 5.2.10 on 2026-01-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("DIGITAL_SIGN", "Digital Sign"),
                            ("KIOSK", "Kiosk"),
                            ("DISPLAY_BOARD", "Display Board"),
                            ("OTHER", "Other"),
                        ],
                        default="DIGITAL_SIGN",
                        max_length=20,
                        verbose_name="device type",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last seen"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional device configuration",
                        verbose_name="metadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "device",
                "verbose_name_plural": "devices",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        editable=False, max_length=64, unique=True, verbose_name="token"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last used"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank for non-expiring token",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
            ],
            options={
                "verbose_name": "device token",
                "verbose_name_plural": "device tokens",
                "ordering": ["-created_at"],
            },
        ),
    ]
