# Generated by Django 5.2.10 on 2026-01-28 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
        ("locations", "0001_initial"),
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="local_authority",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="organisations.localauthority",
                verbose_name="local authority",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Locations this device can display",
                related_name="devices",
                to="locations.location",
                verbose_name="locations",
            ),
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tokens",
                to="api.device",
                verbose_name="device",
            ),
        ),
    ]
