# Generated by Django 5.2.10 on 2026-01-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("NOTICE", "Notice"),
                            ("ADVISORY", "Advisory"),
                            ("RESTRICTION", "Restriction"),
                            ("CLOSURE", "Closure"),
                        ],
                        default="NOTICE",
                        max_length=20,
                        verbose_name="alert type",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="title (English)"),
                ),
                (
                    "title_ga",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="title (Irish)"
                    ),
                ),
                ("message_en", models.TextField(verbose_name="message (English)")),
                (
                    "message_ga",
                    models.TextField(blank=True, verbose_name="message (Irish)"),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank for ongoing alerts",
                        null=True,
                        verbose_name="end date",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_season_long",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a season-long restriction",
                        verbose_name="season long",
                    ),
                ),
                (
                    "beaches_ie_id",
                    models.CharField(
                        blank=True,
                        help_text="Original alert ID from beaches.ie",
                        max_length=50,
                        verbose_name="beaches.ie alert ID",
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw data from beaches.ie API",
                        verbose_name="raw data",
                    ),
                ),
            ],
            options={
                "verbose_name": "alert",
                "verbose_name_plural": "alerts",
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name in English",
                        max_length=200,
                        verbose_name="name (English)",
                    ),
                ),
                (
                    "name_ga",
                    models.CharField(
                        blank=True,
                        help_text="Name in Irish (Gaeilge)",
                        max_length=200,
                        verbose_name="name (Irish)",
                    ),
                ),
                (
                    "beaches_ie_id",
                    models.CharField(
                        help_text="Unique identifier from beaches.ie API, e.g., 'IEWEBWC170_0000_0200'",
                        max_length=50,
                        unique=True,
                        verbose_name="beaches.ie ID",
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("IDENTIFIED", "Identified Bathing Water"),
                            ("NON_IDENTIFIED", "Non-Identified Bathing Water"),
                        ],
                        default="IDENTIFIED",
                        max_length=20,
                        verbose_name="classification",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="latitude"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="longitude"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Description of the location in English",
                        verbose_name="description (English)",
                    ),
                ),
                (
                    "description_ga",
                    models.TextField(
                        blank=True,
                        help_text="Description of the location in Irish",
                        verbose_name="description (Irish)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "has_toilets",
                    models.BooleanField(default=False, verbose_name="toilets"),
                ),
                (
                    "has_parking",
                    models.BooleanField(default=False, verbose_name="parking"),
                ),
                (
                    "has_lifeguard",
                    models.BooleanField(default=False, verbose_name="lifeguard"),
                ),
                (
                    "has_disability_access",
                    models.BooleanField(
                        default=False, verbose_name="disability access"
                    ),
                ),
                (
                    "has_blue_flag",
                    models.BooleanField(default=False, verbose_name="blue flag"),
                ),
                (
                    "dogs_allowed",
                    models.BooleanField(default=True, verbose_name="dogs allowed"),
                ),
            ],
            options={
                "verbose_name": "location",
                "verbose_name_plural": "locations",
                "ordering": ["name_en"],
            },
        ),
        migrations.CreateModel(
            name="WaterQualityData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "sample_date",
                    models.DateField(db_index=True, verbose_name="sample date"),
                ),
                (
                    "ecoli_value",
                    models.IntegerField(
                        blank=True,
                        help_text="E. coli count (cfu/100ml)",
                        null=True,
                        verbose_name="E. coli value",
                    ),
                ),
                (
                    "enterococci_value",
                    models.IntegerField(
                        blank=True,
                        help_text="Intestinal Enterococci count (cfu/100ml)",
                        null=True,
                        verbose_name="Enterococci value",
                    ),
                ),
                (
                    "quality_status",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("SUFFICIENT", "Sufficient"),
                            ("POOR", "Poor"),
                            ("NOT_CLASSIFIED", "Not Classified"),
                        ],
                        default="NOT_CLASSIFIED",
                        max_length=20,
                        verbose_name="quality status",
                    ),
                ),
                (
                    "classification_year",
                    models.IntegerField(
                        blank=True,
                        help_text="Year of the water quality classification",
                        null=True,
                        verbose_name="classification year",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the most recent measurement",
                        verbose_name="is current",
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw data from beaches.ie API",
                        verbose_name="raw data",
                    ),
                ),
            ],
            options={
                "verbose_name": "water quality data",
                "verbose_name_plural": "water quality data",
                "ordering": ["-sample_date"],
                "get_latest_by": "sample_date",
            },
        ),
    ]
