# Generated by Django 5.2.10 on 2026-01-28 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="local_authority",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="organisations.localauthority",
                verbose_name="local authority",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="locations.location",
                verbose_name="location",
            ),
        ),
        migrations.AddField(
            model_name="waterqualitydata",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="water_quality_data",
                to="locations.location",
                verbose_name="location",
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["local_authority", "is_active"],
                name="locations_l_local_a_5ee612_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["beaches_ie_id"], name="locations_l_beaches_ad1add_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["classification"], name="locations_l_classif_c9b20d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["location", "is_active"], name="locations_a_locatio_bbfe36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["start_date", "end_date"], name="locations_a_start_d_d606ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waterqualitydata",
            index=models.Index(
                fields=["location", "-sample_date"],
                name="locations_w_locatio_b5d835_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="waterqualitydata",
            index=models.Index(
                fields=["location", "is_current"], name="locations_w_locatio_314623_idx"
            ),
        ),
    ]
