# Generated by Django 5.2.10 on 2026-01-28 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PosterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("1A", "1A - Identified, No Restrictions"),
                            ("1B", "1B - Identified, Temporary Restrictions"),
                            ("1C", "1C - Identified, Season-Long Restrictions"),
                            ("2A", "2A - Non-Identified, With Restrictions"),
                            ("2B", "2B - Non-Identified, No Restrictions"),
                        ],
                        max_length=5,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of when this template should be used",
                        verbose_name="description",
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("IDENTIFIED", "Identified Bathing Water"),
                            ("NON_IDENTIFIED", "Non-Identified Bathing Water"),
                        ],
                        max_length=20,
                        verbose_name="classification",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "poster template",
                "verbose_name_plural": "poster templates",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Poster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "poster_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Poster"),
                            ("SECTION", "Section Update"),
                        ],
                        default="FULL",
                        max_length=10,
                        verbose_name="poster type",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("A1", "A1 (594 x 841 mm)"),
                            ("A3", "A3 (297 x 420 mm)"),
                            ("A4", "A4 (210 x 297 mm)"),
                            ("A5", "A5 (148 x 210 mm)"),
                        ],
                        default="A1",
                        max_length=5,
                        verbose_name="size",
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[("PORTRAIT", "Portrait"), ("LANDSCAPE", "Landscape")],
                        default="PORTRAIT",
                        max_length=10,
                        verbose_name="orientation",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("ga", "Irish"),
                            ("bilingual", "Bilingual"),
                        ],
                        default="en",
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, upload_to="posters/%Y/%m/", verbose_name="PDF file"
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        upload_to="previews/%Y/%m/",
                        verbose_name="preview image",
                    ),
                ),
                (
                    "water_quality_data",
                    models.JSONField(
                        default=dict,
                        help_text="EPA data snapshot at time of generation",
                        verbose_name="water quality data",
                    ),
                ),
                (
                    "supplementary_content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional content included in the poster",
                        verbose_name="supplementary content",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="generated at"
                    ),
                ),
                (
                    "published_to_ckan",
                    models.BooleanField(
                        default=False, verbose_name="published to CKAN"
                    ),
                ),
                (
                    "ckan_resource_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="CKAN resource ID"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_posters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="generated by",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posters",
                        to="locations.location",
                        verbose_name="location",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posters",
                        to="posters.postertemplate",
                        verbose_name="template",
                    ),
                ),
            ],
            options={
                "verbose_name": "poster",
                "verbose_name_plural": "posters",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="PosterSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("WATER_QUALITY", "Water Quality"),
                            ("ALERTS", "Alerts"),
                            ("QR_CODE", "QR Code"),
                            ("HEADER", "Header"),
                            ("FOOTER", "Footer"),
                        ],
                        max_length=20,
                        verbose_name="section type",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        upload_to="sections/%Y/%m/", verbose_name="PDF file"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="generated at"
                    ),
                ),
                (
                    "poster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="posters.poster",
                        verbose_name="poster",
                    ),
                ),
            ],
            options={
                "verbose_name": "poster section",
                "verbose_name_plural": "poster sections",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="poster",
            index=models.Index(
                fields=["location", "-generated_at"],
                name="posters_pos_locatio_2cb566_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="poster",
            index=models.Index(
                fields=["generated_by", "-generated_at"],
                name="posters_pos_generat_0748e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="poster",
            index=models.Index(
                fields=["-generated_at"], name="posters_pos_generat_d74ef3_idx"
            ),
        ),
    ]
