# Generated by Django 5.2.10 on 2026-01-29 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poster",
            name="custom_notification",
            field=models.TextField(
                blank=True,
                help_text="Custom alert or notification message to display on the poster",
                verbose_name="custom notification",
            ),
        ),
        migrations.AddField(
            model_name="poster",
            name="override_reason",
            field=models.TextField(
                blank=True,
                help_text="Required justification when overriding the recommended template",
                verbose_name="override reason",
            ),
        ),
        migrations.AddField(
            model_name="poster",
            name="recommended_template",
            field=models.ForeignKey(
                blank=True,
                help_text="The template that was recommended by the system",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recommended_for_posters",
                to="posters.postertemplate",
                verbose_name="recommended template",
            ),
        ),
        migrations.AddField(
            model_name="poster",
            name="template_was_overridden",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user chose a different template than recommended",
                verbose_name="template was overridden",
            ),
        ),
    ]
