# Generated by Django 5.2.10 on 2026-01-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("POSTER_GENERATED", "Poster generated"),
                            ("SECTION_UPDATED", "Section updated"),
                            ("USER_LOGIN", "User login"),
                            ("USER_LOGOUT", "User logout"),
                            ("LOCATION_CREATED", "Location created"),
                            ("LOCATION_MODIFIED", "Location modified"),
                            ("ALERT_RECEIVED", "Alert received"),
                            ("DATA_SYNC", "Data synchronised"),
                            ("USER_CREATED", "User created"),
                            ("USER_MODIFIED", "User modified"),
                            ("SETTINGS_CHANGED", "Settings changed"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="action",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="timestamp"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        help_text="Additional details about the action",
                        verbose_name="details",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
