# Generated by Django 6.0.1 on 2026-02-05 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_initial"),
        ("locations", "0002_initial"),
        ("posters", "0002_add_override_and_notification_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="location_audit_logs",
                to="locations.location",
                verbose_name="location",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="poster_audit_logs",
                to="posters.poster",
                verbose_name="poster",
            ),
        ),
    ]
